#!/usr/bin/env python2.7

import datetime
from sqlalchemy import Column, ForeignKey, Integer, String, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy import create_engine
from database_setup import Base, Category, Item


engine = create_engine('sqlite:///catalog.db')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
session = DBSession()


# Categories
session.add_all([
    Category(name="Automotive"),
    Category(name="Baby"),
    Category(name="Books"),
    Category(name="Clothing"),
    Category(name="Electronics"),
    Category(name="Free"),
    Category(name="Furniture"),
    Category(name="Household"),
    Category(name="Toys"),
    Category(name="Video Games")
])


# Items
session.add_all([
    Item(category_id=1,
         user_email="dwagg456@gmail.com",
         title="2012 Ford Focus",
         description="75k miles. Good condition and good gas mileage.",
         price=5000,
         date_posted=datetime.datetime.now()),
    Item(category_id=1,
         user_email="dwagg456@gmail.com",
         title="2013 GMC Terrain",
         description="Low mileage and in great shape. Must see!",
         price=10000,
         date_posted=datetime.datetime.now()),
    Item(category_id=2,
         user_email="dwagg456@gmail.com",
         title="Crib",
         description="Dream on Me convertible crib. Comes with side rails.",
         price=50,
         date_posted=datetime.datetime.now()),
    Item(category_id=2,
         user_email="dwagg456@gmail.com",
         title="Baby swing",
         description="Graco baby swing. Needs batteries.",
         price=10,
         date_posted=datetime.datetime.now()),
    Item(category_id=3,
         user_email="dwagg456@gmail.com",
         title="The Eyes of the Dragon",
         description="Hardback copy of The Eyes of the Dragon",
         price=3,
         date_posted=datetime.datetime.now()),
    Item(category_id=3,
         user_email="dwagg456@gmail.com",
         title="Harry Potter",
         description="Entire 7-book Harry Potter series.",
         price=25,
         date_posted=datetime.datetime.now()),
    Item(category_id=4,
         user_email="dwagg456@gmail.com",
         title="LulaRoe Leggings",
         description="Assortment of LulaRoe leggins for sale.",
         price=20,
         date_posted=datetime.datetime.now()),
    Item(category_id=4,
         user_email="dwagg456@gmail.com",
         title="Coach Purse",
         description="New coach purse. Never used.",
         price=50,
         date_posted=datetime.datetime.now()),
    Item(category_id=5,
         user_email="dwagg456@gmail.com",
         title="50in Vizio Smart TV",
         description="Vizio Smart TV with stand.",
         price=75,
         date_posted=datetime.datetime.now()),
    Item(category_id=5,
         user_email="dwagg456@gmail.com",
         title="Boombox Stereo",
         description="Boombox stereo with CD-player and bluetooth.",
         price=25,
         date_posted=datetime.datetime.now()),
    Item(category_id=6,
         user_email="dwagg456@gmail.com",
         title="Firewood",
         description="Stacks of firewood. Free. Must pick up.",
         price=0,
         date_posted=datetime.datetime.now()),
    Item(category_id=6,
         user_email="dwagg456@gmail.com",
         title="Chairs",
         description="Assorted office chairs.",
         price=0,
         date_posted=datetime.datetime.now()),
    Item(category_id=7,
         user_email="dwagg456@gmail.com",
         title="La-Z-Boy Recliner",
         description="Reclining armchair. Good condition. Must pick-up.",
         price=50,
         date_posted=datetime.datetime.now()),
    Item(category_id=7,
         user_email="dwagg456@gmail.com",
         title="Rocking Chair",
         description="Wooden armchair. Hand-crafted.",
         price=150,
         date_posted=datetime.datetime.now()),
    Item(category_id=8,
         user_email="dwagg456@gmail.com",
         title="Kitchen-Aid Mixer",
         description="Received mixer as a gift and have not used.",
         price=100,
         date_posted=datetime.datetime.now()),
    Item(category_id=8,
         user_email="dwagg456@gmail.com",
         title="Picture Frames",
         description="Brand new box containing 10 picture frames.",
         price=30,
         date_posted=datetime.datetime.now()),
    Item(category_id=9,
         user_email="dwagg456@gmail.com",
         title="Tickle-Me Elmo",
         description="Used tickle-me elmo. Good condition.",
         price=5,
         date_posted=datetime.datetime.now()),
    Item(category_id=9,
         user_email="dwagg456@gmail.com",
         title="Basketball Hoop",
         description="Adjustable plastic basketball hoop. 2-4 feet.",
         price=10,
         date_posted=datetime.datetime.now()),
    Item(category_id=10,
         user_email="dwagg456@gmail.com",
         title="Zelda: Breath of the Wild",
         description="Used Switch copy of Breath of the Wild.",
         price=20,
         date_posted=datetime.datetime.now()),
    Item(category_id=10,
         user_email="dwagg456@gmail.com",
         title="Nintendo Switch",
         description="Selling to get PS4. Comes with two joy-cons.",
         price=100,
         date_posted=datetime.datetime.now())
])


session.commit()
